### ISSUE TITLE
Connect via direct database connection or via API

### ISSUE THREAD

**Issue by rppf** [rppf/dnsman#4]
Should we connect *dnsman* thru direct database connection or thru API. Because most of DNS softwares offers API connection.

**Comment by h4ckedneko** [comment]
*dnsman* needs to consume those APIs for sure because that's the only sane way to manage those DNS software. But I don't understand how it will able to manage via database connection?

**Comment by rppf** [comment]
> But I don't understand how it will able to manage via database connection?

I don't understand either. Some DNS management software do that (via database connection). e.g. [Poweradmin](https://www.poweradmin.org/). I'm going to learn first how to consume APIs using laravel.

**Comment by h4ckedneko** [comment]
I guess it queries the database of PowerDNS to manage it.

It is much easier and sensible to just consume APIs provided by PowerDNS. I suggest we'll use the database only for authentication and reports.
